### PR TITLE
Add transpile task and switch entry points to ES5 output

### PR DESCRIPTION
**Pull request by i-like-robots**
- Moves all modules into `src` folder
- Added task to transpile contents of the `src` folder to a `dist` folder
- Adjusted Bower and NPM entry points to transpiled modules
- Added `prepublish` hook to package manifest

### CODE REVIEW

**Comment by ironsidevsquincy** [comment]
Anything we can do with bower to mean we don't check in `dist`? Some sort of pre-tag git hook?

**Comment by i-like-robots** [comment]
Looking into that ATM - there's always the option to upload a zip with a release which I assume Bower will pick up =/

**Comment by i-like-robots** [comment]
Or we simply no longer publish on Bower... the lazy loading code could be moved into n-ui?

**Comment by i-like-robots** [comment]
Tested on front page and looking 👌

**Comment by i-like-robots** [comment]
Beta released https://github.com/Financial-Times/n-image/tree/v4.3.0-beta.2

Seems to work just fine for front page

**Pull request merged**
