### PR TITLE
Use the matching uuid

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by andygnewman** [comment]
Right location, but wrong fix. Issue is that we get a mix of url's some with -us and some with out so need to turn the (-us) into a non-capturing group. Will do a separate PR for the fix. 

Thanks for pointing out the location of the issue though.

**Comment by JakeChampion** [comment]
@andygnewman Added tests to PR

**Comment by andygnewman** [comment]
Agree the tests work (nice), still think the (-us) should be a non-capturing group though (?:-us), so should only need to take [1] of the regex result.

**Comment by JakeChampion** [comment]
This feature was added in #60

**Pull request closed without merging**
